# Centralized constants for easy tuning.

SCREEN_W = 320
SCREEN_H = 240

FPS = 30
FRAME_MS = 1000 // FPS

COLOR_BG = 0x0000
COLOR_TILE_SOLID = 0x39E7
COLOR_PLAYER = 0x07E0
COLOR_ENEMY_BASIC = 0xF800
COLOR_ENEMY_SHOOTER = 0xFD20
COLOR_BULLET = 0xFFFF
COLOR_UI_BG = 0x0000
COLOR_UI_FG = 0xFFFF

TILE_SIZE = 16
MAX_ENTITIES = 32

GRAVITY = 1
MAX_FALL_SPEED = 8
PLAYER_SPEED_X = 2
PLAYER_GRAVITY = 1
PLAYER_FALL_SPEED_MAX = 8

# Input pins
# Hardware mapping adjusted in Phase 4 manual validation:
# - JOY_X controls left/right in app
# - JOY_Y is vertical (menu/reserved)
JOY_X_PIN = 2
JOY_Y_PIN = 1
JOY_SW_PIN = 15

BTN_A_PIN = 39
BTN_B_PIN = 40
BTN_X_PIN = 38
BTN_Y_PIN = 41

JOY_DEAD_ZONE = 6000
JOY_CALIB_SAMPLES = 32
JOY_CALIB_INTERVAL_MS = 2
JOY_SNAP_TO_ZERO = 3
JOY_SATURATE_THRESHOLD = 96
JOY_SMOOTH_NUM = 3
JOY_SMOOTH_DEN = 4
JOY_AXIS_RAW_MIN = 0
JOY_AXIS_RAW_MAX = 65535
INPUT_DEBOUNCE_MS = 30
SKILL_EDGE_LOCK_MS = 100
SWAP_MIN_INTERVAL_MS = 90

# Camera/parallax mainline.
CAMERA_TEST_MAP_W = 1920
CAMERA_TEST_MAP_H = 240
CAMERA_TEST_FAR_W = 320
CAMERA_TEST_MID_W = 640
CAMERA_TEST_NEAR_W = 960
CAMERA_TEST_MODE = "ROWS_SAFE_PROGRESSIVE"
CAMERA_TEST_STEP = 4
FULL_BUFFER_ENABLE_WORLD = True
FULL_BUFFER_ENABLE_SPRITE = True
FULL_BUFFER_ENABLE_HUD = True
FULL_BUFFER_DBG_EVERY = 60
CAMERA_SPI_TEST_DBG_EVERY = 60
CAMERA_TEST_PLAYER_W = 12
CAMERA_TEST_PLAYER_H = 16
CAMERA_TEST_PLAYER_START_X = 1584
CAMERA_TEST_PLAYER_START_Y = 144
CAMERA_TEST_ROOT_BG_FAR_RGB565 = "/sd/game/picture/backgound/bg_far_wire.rgb565"
CAMERA_TEST_ROOT_BG_MID_RGB565 = "/bg_mid.rgb565"
CAMERA_TEST_RGB565_CHUNK_H = 40
CAMERA_TOP_HUD_ENABLED = False
CAMERA_PLAYER_SPRITE_ENABLED = True
CAMERA_PLAYER_SPRITE_DRAW_MODE = "COMPOSE"
CAMERA_PLAYER_SPRITE_COMPOSE_IMPL = "C_API"
CAMERA_PLAYER_SPRITESHEET_PATH = "/sd/game/picture/player/player_wire.rgb565"
CAMERA_PLAYER_COLORKEY_RGB565 = 0xF81F
CAMERA_TEST_COORD_UPDATE_EVERY = 15
CAMERA_TEST_TOP_HUD_W = 112
CAMERA_TEST_TOP_HUD_H = 16
CAMERA_RUNTIME_VERBOSE = True
CAMERA_TEST_STEP4_DBG_EVERY = 1000000
CAMERA_TEST_STEP4_PROFILE_EVERY = 300
CAMERA_RENDER_PROFILE_DETAIL = False
CAMERA_UPDATE_PROFILE_DETAIL = True
CAMERA_STALL_FRAME_US = 1000000000
CAMERA_FULL_BULK_DOUBLE_BUFFER = True
CAMERA_FULL_BULK_WIRE_ORDER = True
CAMERA_BAND_PIPELINE_NATIVE = True
CAMERA_BAND_PIPELINE_H = 48
CAMERA_BAND_TAIL_OVERLAP_UPDATE = True
CAMERA_PROBE_DISABLE_FAR_BAND = False
CAMERA_PROBE_DISABLE_TILEMAP_BAND = False
CAMERA_PROBE_DISABLE_OBJECT_BAND = False
CAMERA_PROBE_DISABLE_ENEMY_BAND = False
CAMERA_PROBE_DISABLE_OVERLAY_BAND = False

# Foreground floor layer (map1) settings.
FLOOR_LAYER_ENABLED = False
FLOOR_LAYER_RGB565_PATH = "game/picture/backgound/map1.rgb565"
FLOOR_LAYER_MASK_PATH = "game/picture/backgound/map1.mask"
FLOOR_LAYER_W = 960
FLOOR_LAYER_H = 240
FLOOR_SCROLL_FACTOR = 1.0
FLOOR_LAYER_SCREEN_Y = SCREEN_H - FLOOR_LAYER_H
# Horizontal start offset for floor source sampling.
# Positive value shifts initial view rightward (useful when key landmarks are mid-map).
FLOOR_SCROLL_X_OFFSET = 0
# Enable C masked compose path (rollback to previous verified scrolling behavior).
FLOOR_USE_C_COMPOSE = True

# Tilemap (16x16) settings.
# app_camera_test.py uses embedded tile index CSV and this tileset atlas.
TILEMAP_ENABLED = True
TILESET_RGB565_PATH = "game/Tilemap/tilemap_all_wire.rgb565"
TILEMAP_CSV_PATH = "game/Tilemap/map_tilemap.csv"
TILESET_ATLAS_W = 128
TILESET_ATLAS_H = 128
OBJECTS_CSV_PATH = "game/picture/object/objects.csv"
OBJECT_ANIMATIONS_JSON_PATH = "game/picture/object/object_animations.json"
OBJECTS_ATLAS_RGB565_PATH = "game/picture/object/object_altes_wire.rgb565"
OBJECTS_ATLAS_W = 256
OBJECTS_ATLAS_H = 256
ENEMY_CSV_PATH = "game/picture/enemy/enemies.csv"
ENEMY_SHEET_RGB565_PATH = "game/picture/enemy/enemy_bow_animation_wire.rgb565"
ENEMY_MONK_SHEET_RGB565_PATH = "game/picture/enemy/enemy_monk_wire.rgb565"
ENEMY_MONK_FRAME_W = 32
ENEMY_MONK_FRAME_H = 48
ENEMY_MONK_FRAME_COUNT = 4
ENEMY_MONK_SHEET_ROWS = 2
ENEMY_MONK_FRAME_HOLD = 6
ENEMY_MONK_ORB_ATLAS_RGB565_PATH = "game/picture/object/object_altes_wire.rgb565"
ENEMY_MONK_ORB_ATLAS_W = 256
ENEMY_MONK_ORB_ATLAS_H = 256
ENEMY_SHEET_W = 320
ENEMY_SHEET_H = 96
ENEMY_FRAME_W = 32
ENEMY_FRAME_H = 32
ENEMY_FRAME_HOLD = 3
ENEMY_DETECT_RANGE_X = 160
ENEMY_FLEE_RANGE_X = 80
ENEMY_DETECT_RANGE_Y = 24
ENEMY_MOVE_SPEED = PLAYER_SPEED_X
ENEMY_GRAVITY_STEP = 2
ENEMY_SHOOT_INTERVAL = 15
ENEMY_SHOOT_FIRE_FRAME = 4
ENEMY_BULLET_W = 16
ENEMY_BULLET_H = 16
ENEMY_BULLET_SRC_X = 240
ENEMY_BULLET_SRC_Y_RIGHT = 0
ENEMY_BULLET_SRC_Y_LEFT = 16
ENEMY_BULLET_SPEED = 3
ENEMY_MAX_BULLETS = 4
ENEMY_UPDATE_MARGIN_X = 160
ENEMY_UPDATE_MARGIN_Y = 80
ENEMY_RENDER_MARGIN_X = 48
ENEMY_RENDER_MARGIN_Y = 32
ENEMY_BULLET_CULL_MARGIN = 32
MONK_HOVER_ENABLED = True
MONK_HOVER_MIN_X = 1616
MONK_HOVER_MAX_X = 1887
MONK_HOVER_BASE_Y = 55
MONK_HOVER_AMP = 39
MONK_HOVER_PHASE_STEP = 1
MONK_HOVER_WAVE_AMP_X = 0
MONK_HOVER_WAVE_AMP_Y = 0
MONK_ATTACK_ENABLED = True
MONK_ATTACK_SPEED = 6
MONK_INTRO_ENABLED = True
MONK_INTRO_DROP_SPEED = 3
MONK_INTRO_TARGET_Y = 56
MONK_INTRO_START_OFFSET_Y = 96
MONK_RESPAWN_REINTRO_MIN_X = 1500
MONK_HOVER_RETARGET_FRAMES = 30
MONK_HOVER_TARGET_EPS = 12
MONK_HOVER_SPEED_Q8 = 512
OBJECTS_COMPOSE_IMPL = "C_API"
CAMERA_OBJECT_COLORKEY_ENABLE = True
CAMERA_OBJECT_COLORKEY_RGB565 = 0xF81F
OBJECT_GRAVITY_ENABLED = True
OBJECT_GRAVITY_STEP = 2
OBJECT_GRAVITY_UPDATE_MARGIN_X = 160
OBJECT_GRAVITY_UPDATE_MARGIN_Y = 80
RESPAWN_DEATH_MARGIN = 48
RESPAWN_CAMERA_PAN_STEP = 12
RESPAWN_ANCHOR_OFFSET_Y = 32
RESPAWN_ANCHOR_ANIM_ID = "resurrection_anchor"

SAVE_PATH = "/sd/game/save/save0.json"
