# Centralized constants for easy tuning.

SCREEN_W = 320
SCREEN_H = 240

FPS = 30
FRAME_MS = 1000 // FPS

COLOR_BG = 0x0000
COLOR_TILE_SOLID = 0x39E7
COLOR_PLAYER = 0x07E0
COLOR_ENEMY_BASIC = 0xF800
COLOR_ENEMY_SHOOTER = 0xFD20
COLOR_BULLET = 0xFFFF
COLOR_UI_BG = 0x0000
COLOR_UI_FG = 0xFFFF

TILE_SIZE = 16
MAX_ENTITIES = 32

GRAVITY = 1
MAX_FALL_SPEED = 8
PLAYER_SPEED_X = 2

# Input pins
# Hardware mapping adjusted in Phase 4 manual validation:
# - JOY_X controls left/right in app
# - JOY_Y is vertical (menu/reserved)
JOY_X_PIN = 2
JOY_Y_PIN = 1
JOY_SW_PIN = 15

BTN_A_PIN = 38
BTN_B_PIN = 39
BTN_X_PIN = 40
BTN_Y_PIN = 41

JOY_DEAD_ZONE = 6000
JOY_CALIB_SAMPLES = 32
JOY_CALIB_INTERVAL_MS = 2
JOY_SNAP_TO_ZERO = 3
JOY_SATURATE_THRESHOLD = 96
JOY_SMOOTH_NUM = 3
JOY_SMOOTH_DEN = 4
JOY_AXIS_RAW_MIN = 0
JOY_AXIS_RAW_MAX = 65535
INPUT_DEBOUNCE_MS = 30
SKILL_EDGE_LOCK_MS = 100

# Acceptance stage selector:
# - "PHASE7": run Phase 7 near/far swap validation
# - "PHASE8": run Phase 8 UI/save/startup validation
# - "PHASE6": run Phase 6 deterministic entity/actor validation
# - "PHASE5": run existing Phase 5 flow
# - "RED_SCREEN_TEST": full-screen red display smoke test
# - "PHASE_CAMERA_TEST": standalone camera/parallax validation path
PHASE_ACCEPTANCE_STAGE = "PHASE_CAMERA_TEST"

# Standalone camera/parallax test (must not alter Phase 7 baseline).
CAMERA_TEST_MAP_W = 960
CAMERA_TEST_MAP_H = 240
CAMERA_TEST_FAR_W = 320
CAMERA_TEST_MID_W = 640
CAMERA_TEST_NEAR_W = 960
CAMERA_TEST_MODE = "ROWS_SAFE_PROGRESSIVE"
CAMERA_TEST_STEP = 4
FULL_BUFFER_ENABLE_WORLD = True
FULL_BUFFER_ENABLE_SPRITE = True
FULL_BUFFER_ENABLE_HUD = True
FULL_BUFFER_DBG_EVERY = 60
CAMERA_SPI_TEST_PATH = "ROWS"
CAMERA_SPI_TEST_DBG_EVERY = 60
CAMERA_TEST_PNG_SINGLE_STAGE = 1  # 1=near, 2=near+mid, 3=near+mid+far
CAMERA_TEST_STRIP_H = 30
CAMERA_TEST_MANUAL_FRAMES = 900
CAMERA_TEST_PLAYER_W = 12
CAMERA_TEST_PLAYER_H = 16
CAMERA_TEST_PLAYER_START_X = 32
CAMERA_TEST_PLAYER_START_Y = 208
CAMERA_TEST_BG_DIR = "/sd/game/picture/backgound"
CAMERA_TEST_BG_FAR = CAMERA_TEST_BG_DIR + "/bg_far.png"
CAMERA_TEST_BG_MID = CAMERA_TEST_BG_DIR + "/bg_mid.png"
CAMERA_TEST_BG_NEAR = CAMERA_TEST_BG_DIR + "/bg_near.png"
CAMERA_TEST_BG_FAR_RGB565 = CAMERA_TEST_BG_DIR + "/bg_far.rgb565"
CAMERA_TEST_BG_MID_RGB565 = CAMERA_TEST_BG_DIR + "/bg_mid.rgb565"
CAMERA_TEST_BG_NEAR_RGB565 = CAMERA_TEST_BG_DIR + "/bg_near.rgb565"
CAMERA_TEST_ROOT_BG_FAR_RGB565 = "/bg_far.rgb565"
CAMERA_TEST_ROOT_BG_MID_RGB565 = "/bg_mid.rgb565"
CAMERA_TEST_ROOT_TEST_BARS_RGB565 = "/test_bars.rgb565"
CAMERA_TEST_ROOT_TEST_GRID_RGB565 = "/test_grid.rgb565"
CAMERA_TEST_RGB565_CHUNK_H = 40
CAMERA_TOP_HUD_ENABLED = False
CAMERA_PLAYER_SPRITE_ENABLED = True
CAMERA_PLAYER_SPRITE_DRAW_MODE = "COMPOSE"
CAMERA_PLAYER_SPRITE_COMPOSE_IMPL = "PYTHON"
CAMERA_TEST_COORD_UPDATE_EVERY = 15
CAMERA_TEST_TOP_HUD_W = 112
CAMERA_TEST_TOP_HUD_H = 16
CAMERA_TEST_STEP4_DBG_EVERY = 15
CAMERA_TEST_STEP4_PROFILE_EVERY = 60
CAMERA_DIRTY_RECT_EXPERIMENT = True
CAMERA_DIRTY_FALLBACK_ON_CAMERA_MOVE = True
CAMERA_DIRTY_BAND_FULL_WIDTH = True

# Foreground floor layer (map1) settings.
FLOOR_LAYER_ENABLED = True
FLOOR_LAYER_RGB565_PATH = "game/picture/backgound/map1.rgb565"
FLOOR_LAYER_MASK_PATH = "game/picture/backgound/map1.mask"
FLOOR_LAYER_W = 960
FLOOR_LAYER_H = 240
FLOOR_SCROLL_FACTOR = 1.0
FLOOR_LAYER_SCREEN_Y = SCREEN_H - FLOOR_LAYER_H

# Phase 5 acceptance mode:
# - "TEST": deterministic scripted validation
# - "MANUAL": real joystick validation flow
# - "LEFT_EDGE_STATIC": draw fixed blocks at x=0/4/8 (no physics/input)
# - "AUTO": TEST when max_frames is provided, otherwise MANUAL
PHASE5_ACCEPTANCE_MODE = "LEFT_EDGE_STATIC"
PHASE5_TEST_FRAMES = 300
PHASE5_MANUAL_FRAMES = 900
PHASE5_LEFT_EDGE_TEST_FRAMES = 900
PHASE5_LEFT_EDGE_BLOCK_W = 16
PHASE5_LEFT_EDGE_BLOCK_H = 16
PHASE5_LEFT_EDGE_BLOCK_Y = 72
PHASE5_MANUAL_AXIS_ACTIVE = 30
PHASE5_MANUAL_AXIS_STOP = 8
PHASE5_MANUAL_STOP_FRAMES = 10

# Phase 6 acceptance mode:
# - "TEST": deterministic entity/actor validation (default)
# - "MANUAL": interactive observation mode
# - "AUTO": TEST when max_frames is provided, otherwise MANUAL
PHASE6_ACCEPTANCE_MODE = "MANUAL"
PHASE6_TEST_FRAMES = 300
PHASE6_MANUAL_FRAMES = 900
PHASE6_BULLET_POOL_SIZE = 6
PHASE6_BULLET_MAX_FRAMES = 24
PHASE6_SHOOTER_INTERVAL_FRAMES = 12
PHASE6_BULLET_SPEED = 4

# Phase 7 acceptance mode:
# - "TEST": deterministic near/far swap validation
# - "MANUAL": interactive swap observation
# - "AUTO": TEST when max_frames is provided, otherwise MANUAL
PHASE7_ACCEPTANCE_MODE = "MANUAL"
PHASE7_TEST_FRAMES = 320
PHASE7_MANUAL_FRAMES = 900
PHASE7_SHOOTER_INTERVAL_FRAMES = 12
PHASE7_TEST_SHOOTER_INTERVAL_FRAMES = 600

# Deterministic trigger schedule (frame index)
PHASE7_TEST_NEAR_START = 20
PHASE7_TEST_FAR_START = 40
PHASE7_TEST_NO_TARGET_START = 60
PHASE7_TEST_HOLD_X_START = 80
PHASE7_TEST_NO_CD_B_FRAME = 100
PHASE7_TEST_NO_CD_X_FRAME = 104
PHASE7_TEST_AIR_SWAP_FRAME = 130

# Phase 8 acceptance mode:
# - "TEST": deterministic UI/save validation
# - "MANUAL": interactive HUD/save validation
# - "AUTO": TEST when max_frames is provided, otherwise MANUAL
PHASE8_ACCEPTANCE_MODE = "MANUAL"
PHASE8_TEST_FRAMES = 360
PHASE8_MANUAL_FRAMES = 900
PHASE8_HUD_HEIGHT = 16
PHASE8_SAVE_STATUS_TTL_FRAMES = 45

# Deterministic trigger schedule (frame index)
PHASE8_TEST_DEBUG_ON_FRAME = 8
PHASE8_TEST_SAVE_FRAME = 22
PHASE8_TEST_DEBUG_OFF_FRAME = 44
PHASE8_TEST_NEAR_FRAME = 70
PHASE8_TEST_FAR_FRAME = 96
PHASE8_TEST_SAVE_LOAD_FRAME = 128

STAGE_PATH = "/sd/game/maps/stage01.json"
SAVE_PATH = "/sd/game/save/save0.json"
