set(SDKCONFIG_DEFAULTS
    boards/sdkconfig.base
    boards/sdkconfig.spiram_sx
    boards/ESP32_GENERIC_S3/sdkconfig.board
    boards/sdkconfig.240mhz
    boards/sdkconfig.spiram_oct
    boards/ESP32_GENERIC_S3/sdkconfig.nobt
)

list(APPEND MICROPY_DEF_BOARD
    MICROPY_HW_BOARD_NAME="ESP32_GENERIC_S3_SPIRAM_OCT_NOBT_GAME"
    MICROPY_PY_BLUETOOTH=0
    MICROPY_PY_ESPNOW=0
    MICROPY_PY_NETWORK=0
    MICROPY_PY_WEBREPL=0
    MICROPY_PY_SSL=0
    MICROPY_PY_WEBSOCKET=0
    MICROPY_HW_ENABLE_USBDEV=0
    MICROPY_PY_MACHINE_I2S=0
    MICROPY_PY_MACHINE_I2C_TARGET=0
)
