// Automatically generated by make_root_pointers.py.

const char *readline_hist[(8)];
mp_obj_list_t mp_sys_argv_obj;
mp_obj_t bluetooth;
mp_obj_t dupterm_objs[(1)];
mp_obj_t machine_i2c_target_mem_obj[(2)];
mp_obj_t machine_pin_irq_handler[(49)];
mp_obj_t persistent_code_root_pointers;
mp_obj_t sys_mutable[MP_SYS_MUTABLE_NUM];
mp_obj_t usbd;
mp_sched_item_t sched_queue[(8)];
struct _esp32_pcnt_obj_t *esp32_pcnt_obj_head;
struct _esp_espnow_obj_t *espnow_singleton;
struct _machine_i2s_obj_t *machine_i2s_obj[(2U)];
struct _machine_timer_obj_t *machine_timer_obj_head;
struct _mp_bluetooth_nimble_root_pointers_t *bluetooth_nimble_root_pointers;
struct _mp_vfs_mount_t *vfs_cur;
struct _mp_vfs_mount_t *vfs_mount_table;
void *machine_i2c_target_irq_obj[(2)];
void *machine_uart_objs[(3)];
